// Copyright (c) 2026 litongshuai
// SPDX-License-Identifier: MIT OR Apache-2.0

import 'package:flutter/material.dart';
import 'design_tokens.dart';

class AppColors {
  static ColorScheme lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: DesignTokens.primary500,
    onPrimary: Colors.white,
    primaryContainer: DesignTokens.primary100,
    onPrimaryContainer: DesignTokens.primary700,
    secondary: DesignTokens.accent500,
    onSecondary: Colors.white,
    secondaryContainer: DesignTokens.accent100,
    onSecondaryContainer: DesignTokens.accent500,
    tertiary: DesignTokens.primary400,
    onTertiary: Colors.white,
    tertiaryContainer: DesignTokens.primary50,
    onTertiaryContainer: DesignTokens.primary700,
    error: DesignTokens.error,
    onError: Colors.white,
    errorContainer: Color(0xFFfee2e2),
    onErrorContainer: DesignTokens.error,
    surface: Colors.white,
    onSurface: DesignTokens.gray900,
    surfaceContainerLowest: Colors.white,
    surfaceContainerLow: DesignTokens.gray50,
    surfaceContainer: DesignTokens.gray100,
    surfaceContainerHigh: DesignTokens.gray200,
    surfaceContainerHighest: DesignTokens.gray300,
    onSurfaceVariant: DesignTokens.gray500,
    outline: DesignTokens.gray200,
    outlineVariant: DesignTokens.gray300,
    shadow: Color.fromRGBO(0, 0, 0, 0.1),
    scrim: Color.fromRGBO(0, 0, 0, 0.3),
    inverseSurface: DesignTokens.gray900,
    onInverseSurface: Colors.white,
    inversePrimary: DesignTokens.primary400,
  );

  static ColorScheme darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: DesignTokens.darkPrimary500,
    onPrimary: Colors.white,
    primaryContainer: DesignTokens.darkPrimary700,
    onPrimaryContainer: DesignTokens.darkPrimary500,
    secondary: DesignTokens.accent400,
    onSecondary: Colors.white,
    secondaryContainer: DesignTokens.accent500,
    onSecondaryContainer: DesignTokens.accent400,
    tertiary: DesignTokens.primary400,
    onTertiary: Colors.white,
    tertiaryContainer: DesignTokens.darkPrimary700,
    onTertiaryContainer: DesignTokens.darkPrimary500,
    error: DesignTokens.error,
    onError: Colors.white,
    errorContainer: Color(0xFF7f1d1d),
    onErrorContainer: Color(0xFFfecaca),
    surface: DesignTokens.darkSurface,
    onSurface: DesignTokens.darkTextPrimary,
    surfaceContainerLowest: DesignTokens.darkBackground,
    surfaceContainerLow: DesignTokens.darkBackground,
    surfaceContainer: DesignTokens.darkSurface,
    surfaceContainerHigh: Color(0xFF334155),
    surfaceContainerHighest: DesignTokens.darkBorder,
    onSurfaceVariant: DesignTokens.darkTextSecondary,
    outline: DesignTokens.darkBorder,
    outlineVariant: Color(0xFF475569),
    shadow: Color.fromRGBO(0, 0, 0, 0.3),
    scrim: Color.fromRGBO(0, 0, 0, 0.5),
    inverseSurface: DesignTokens.gray100,
    onInverseSurface: DesignTokens.gray900,
    inversePrimary: DesignTokens.primary700,
  );
}
